### ISSUE TITLE
Maybe such a good project could be packaged for docker

### ISSUE THREAD

**Issue by gcaiso9002** [jlnbxn/markdownloader#2]
emmm，because I have been using obsidian, and the software does not provide a web clipping collection like joplin. I've thought about writing a similar Flask in python before, but it's nowhere near as good as yours. So, is it possible to package this into a docker application so that people can use the project more easily?

**Comment by jlnbxn** [comment]
Hello and thank you! The main idea behind this app is that it doesn't require any server to pull off the client side fetching of resources that would normally be prevented by CORS restrictions. As I've written, this relies mostly on Netlifys feature of allowing you to proxy links through their CDN, thus removing those restrictions and being able to access those resources directly from within the browser (which is what Markdownloader does when downloading images from other sites). Dockerizing the app wouldn't make much sense since wherever you installed the container, you would essentially have access to a server where CORS doesn't apply anyway.

Another approach would be to use a web extension, where you can send fetch requests without from the background without CORS blocking you (which is how [SingleFile](https://github.com/gildas-lormeau/SingleFile) does it). 

I assume it would be possible to add functionality to this site so that you could get the downloaded zip by simply adding a link to the end of the Markdownloader URL and navigating to it, which could be further simplified by then turning it into a bookmarklet that creates an Obsidian file! But that is basically what [this gist](https://gist.github.com/kepano/90c05f162c37cf730abb8ff027987ca3) does.

Maybe that's what you need?

While it doesn't download images directly like Markdownloader does, you'd have to get them into Obsidian some other way anyhow. Creating a single Markdown file with embedded images would require them to be in Base64, which may or may not have other drawbacks when working with Obsidian (which I never did, so I can't comment on that). But there appears to be a plugin that resolves this. (See the gists' readme)

Hope that helps!
